### ISSUE TITLE
TypeError: Cannot read property 'setFailed' of undefined

### ISSUE THREAD

**Issue by matthew-petrie** [matthew-petrie/shopify-theme-actions#27]
```
(node:1715) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setFailed' of undefined
    at handleError (/home/runner/work/_actions/matthew-petrie/shopify-theme-actions/0.0.5/dist/index.js:10328:23)
    at /home/runner/work/_actions/matthew-petrie/shopify-theme-actions/0.0.5/dist/index.js:10417:22
(node:1715) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1715) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by matthew-petrie** [comment]
fixed in #28
